name: Test Arm
on:
    workflow_dispatch:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Hello World
      run: |
        ./install-brew-cli.sh
        echo "Hello World"
        head -n 1 /etc/os-release
        uname -a
        brew --version
    # - name: test qemu
    #   uses: pguyot/arm-runner-action@v2
    #   with:
    #     commands: |
    #       echo "Hello World"
    #       head -n 1 /etc/os-release
    #       uname -a
