name: Test Arm
on:
    workflow_dispatch:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: PWD
      run: |
        pwd
    - name: Install 01
      run: |
        ./install-01-dependencies.sh
    - name: Install 02
      run: |
        ./install-02-ruby.sh
    - name: Install 03
      run: |
        ./install-03-brew.sh
    - name: Test w/o brew
      run: |
        echo "Hello World"
        head -n 1 /etc/os-release
        uname -a
    - name: Test w/ brew
      run: |
        brew --version
    # - name: test qemu
    #   uses: pguyot/arm-runner-action@v2
    #   with:
    #     commands: |
    #       echo "Hello World"
    #       head -n 1 /etc/os-release
    #       uname -a
